// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkG7bJ271gHv7Yh3vLvOZtqHzSRWfrMn0',
    appId: '1:852608203033:web:cfd2f4cc3a4ab4706a2d88',
    messagingSenderId: '852608203033',
    projectId: 'khuloset-beta-123',
    authDomain: 'khuloset-beta-123.firebaseapp.com',
    storageBucket: 'khuloset-beta-123.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP_H6SdUIc2E2wZldYGoxpDv_dcEVHgTg',
    appId: '1:852608203033:android:80e35660574f3d9f6a2d88',
    messagingSenderId: '852608203033',
    projectId: 'khuloset-beta-123',
    storageBucket: 'khuloset-beta-123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6w2fqec_zv9PEHXh12jmDY018MI1rb2k',
    appId: '1:852608203033:ios:fe2500ede52e4cec6a2d88',
    messagingSenderId: '852608203033',
    projectId: 'khuloset-beta-123',
    storageBucket: 'khuloset-beta-123.appspot.com',
    iosBundleId: 'com.example.khulosetBeta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6w2fqec_zv9PEHXh12jmDY018MI1rb2k',
    appId: '1:852608203033:ios:8f10d2230e2708416a2d88',
    messagingSenderId: '852608203033',
    projectId: 'khuloset-beta-123',
    storageBucket: 'khuloset-beta-123.appspot.com',
    iosBundleId: 'com.example.khulosetBeta.RunnerTests',
  );
}
